# Generated by Django 6.0.1 on 2026-01-21 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Код валюты')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Баланс')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='billing.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Балансы',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('conversion', 'Конвертация валюты'), ('service_spend', 'Покупка услуги'), ('account_topup', 'Пополнение аккаунта')], max_length=50, verbose_name='Тип транзакции')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Сумма')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=16, max_digits=35, null=True, verbose_name='Обменный курс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_transactions', to='billing.currency', verbose_name='Валюта')),
                ('gross_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gross_currency_transactions', to='billing.currency', verbose_name='Валюта для обмена')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
